# Generated by Django 4.1 on 2023-02-26 18:53

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('titol', models.CharField(max_length=300, verbose_name='Asunto')),
                ('data', models.DateTimeField(default=timezone.now)),
                ('description', models.TextField(blank=True)),
                ('preu', models.IntegerField(verbose_name='Precio')),
        
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('adress', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=15, verbose_name='Codigo Postal')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefono de Conatcto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('data_com', models.DateField(default=timezone.now)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallapop_app.usuari')),
                ('titol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallapop_app.anunci')),
            ],
        ),
        migrations.AddField(
            model_name='anunci',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallapop_app.usuari'),
        ),
    ]
