# Generated by Django 4.1 on 2023-02-27 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallapop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentari',
            name='data_com',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
