# Generated by Django 4.1 on 2023-03-07 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallapop_app', '0003_alter_anunci_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentari',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuari',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anunci',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentari',
            name='data_com',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
