# Generated by Django 4.1 on 2023-03-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapop_app', '0004_comentari_description_usuari_user_alter_anunci_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='bio',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
