# Generated by Django 4.1 on 2023-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapop_app', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
