# Generated by Django 4.1 on 2023-03-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapop_app', '0007_alter_usuari_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunci',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
