# Generated by Django 4.1 on 2023-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapop_app', '0009_alter_anunci_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentari',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentari',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
